version: 2

project_name: cw-trainer

before:
  hooks:
    - go mod tidy

builds:
  - id: cw-trainer
    main: ./cmd/cw-trainer
    binary: cw-trainer
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README_en.md
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: shaposhnikoff
    name: cw-trainer
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Tag}}"
